### ISSUE TITLE
Not working on macvim

### ISSUE THREAD

**Issue by sunchess** [nowk/genericdc#2]
Hi, I'm trying to run your color scheme on my mac vim and it not working for me.
Just sets default colors. Can you give me a point where the problem is.

Thanks.

**Comment by nowk** [comment]
Hey @sunchess. Currently, this is a `term` vim only color scheme.

**Comment by sunchess** [comment]
very sad about it. I am in love to your color scheme :)
Cheers!

**Comment by nowk** [comment]
You can try this commit 6461667c59252d080da69acc3a8fb961c2e1646d. I had gui colors, but couldn't maintain the color accuracy since I don't have or use a gui vim very often. Colors may not be exactly the same, but should be pretty close, at least for the dark version.

**Comment by sunchess** [comment]
Thanks a lot!
