### ISSUE TITLE
Comments and methods

### ISSUE THREAD

**Issue by ghost** [nowk/genericdc#3]
I really like the theme overall, however whenever I set it (using :colorscheme genericdc) the comments and method names have a different background color than the rest of the text. This makes it look like the comments/method names are highlighted and it doesn't look as good. The reason I created an issue was because I didn't see this in any of the previews. Is there a simple way I could fix it (i.e. :highlight Comment ctermbg=#______)?

I'm running manjaro linux using the xfce terminal.

**Comment by nowk** [comment]
@dwoodwardgb, This is most likely a product of the `cterm=italic` I have in there. If you can get italics to work in terminal vim, you should be good to go. Else you could do `:hi comment cterm=none`.
